version: '3.1'
services: 
  db:
    image: mariadb:latest
    restart: always
    container_name: mariadb
    environment:
        MYSQL_ROOT_PASSWORD: root
    volumes:
      - /docker/mariadb/db_data:/var/lib/mysql
      - /docker/mariadb/my.cnf:/etc/mysql/my.cnf
    ports:
      - 63306:3306